"""
dep_extractor/output/report_writer.py
=======================================
Phase 4 — Generates the combined_requirements.txt output file.

Educational: This is a "pure I/O" module — it receives data, writes a file,
and does nothing else. No logic, no subprocess calls, no imports from
the install layer. This strict separation means:

  1. The file writing is independently testable (just check the output file)
  2. Any caller (CLI, tests, GUI) can reuse it without triggering side effects
  3. The format can be updated here without touching any other module

The output file format is backward-compatible with the monolith — existing
scripts and tools that read combined_requirements.txt will continue to work.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from dep_extractor.models import (
    AuditData,
    AuditReport,
    NormalizedRequirement,
    UrlValidationResult,
)

logger = logging.getLogger(__name__)

# Header written at the top of every generated file
_FILE_HEADER = """\
# ============================================================
# Combined Requirements — Generated by dep_extractor v2.0
# Generated : {timestamp}
# Root      : {root}
# OS        : {os}
# CUDA      : {cuda}
# Python    : {python}
# ============================================================
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_combined_requirements(
    output_path: Path,
    packages: list[NormalizedRequirement],
    specialized: list[NormalizedRequirement],
    extra_indices: list[str],
    audit: AuditData,
    audit_report: AuditReport,
    url_results: list[UrlValidationResult] | None = None,
    root: Path | None = None,
) -> None:
    """
    Write the combined requirements file to `output_path`.

    File structure:
        1. File header with generation metadata
        2. Extra index URLs (--extra-index-url directives)
        3. Standard packages (sorted alphabetically)
        4. Specialized requirements (URLs, local paths, wheels)
        5. Audit / diagnostic comments (conflicts, untracked wheels)

    Args:
        output_path:  Destination file path (will be created/overwritten).
        packages:     Standard normalized requirements.
        specialized:  URL/path/wheel requirements.
        extra_indices: PyTorch hardware index URLs to include.
        audit:        Hardware audit data for the header.
        audit_report: Aggregated diagnostics for the audit section.
        url_results:  Optional URL validation results (written as comments).
        root:         Root path for the header metadata comment.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []

    # 1. File header
    lines.extend(_build_header(audit, root))

    # 2. Extra index URLs
    if extra_indices:
        lines.append("\n# --- PyTorch Hardware Index URLs ---\n")
        for idx in extra_indices:
            lines.append(f"--extra-index-url {idx}\n")

    # 3. Standard packages
    lines.append("\n# --- Standard Dependencies ---\n")
    sorted_pkgs = sorted(packages, key=lambda r: r.name)
    for req in sorted_pkgs:
        lines.append(f"{req}\n")

    # 4. Specialized requirements (URLs, local paths)
    if specialized:
        lines.append("\n# --- Specialized Dependencies (URLs / Local Paths) ---\n")
        for req in specialized:
            # Comment out incompatible wheels so pip/uv doesn't crash on them
            if req.is_wheel and req.wheel_metadata and not req.wheel_metadata.is_compatible:
                lines.append(f"# [PLATFORM INCOMPATIBLE] {req.raw}\n")
            else:
                lines.append(f"{req.raw}\n")

    # 5. Audit section
    lines.extend(_build_audit_section(audit_report, url_results))

    # Write atomically (write to temp, then rename) to avoid partial files
    tmp_path = output_path.with_suffix(".tmp")
    try:
        tmp_path.write_text("".join(lines), encoding="utf-8")
        tmp_path.replace(output_path)
        logger.info("Wrote combined requirements to: %s", output_path)
    except Exception as exc:
        logger.error("Failed to write output file: %s", exc)
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)
        raise


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _build_header(audit: AuditData, root: Path | None) -> list[str]:
    """Returns the formatted file header lines."""
    return [
        _FILE_HEADER.format(
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            root=str(root) if root else "unknown",
            os=f"{audit.os} {audit.os_release}",
            cuda=audit.cuda_version or "not detected",
            python=audit.python_target_version,
        )
    ]


def _build_audit_section(
    report: AuditReport,
    url_results: list[UrlValidationResult] | None,
) -> list[str]:
    """
    Builds the diagnostic comment section at the bottom of the output file.

    All lines in this section are comments (start with #) so the file
    remains usable as a pip/uv requirements input even with diagnostics present.
    """
    lines: list[str] = ["\n# ============================================================\n"]
    lines.append("# DIAGNOSTIC AUDIT REPORT (comments only — safe to ignore)\n")
    lines.append("# ============================================================\n")

    # URL validation results
    if url_results:
        failed = [r for r in url_results if not r.is_valid]
        lines.append(f"\n# URL Validation: {len(url_results)} checked, {len(failed)} failed\n")
        for r in url_results:
            mark = "OK" if r.is_valid else f"FAIL: {r.error}"
            lines.append(f"#   [{mark}] {r.url[:80]}\n")

    # Version conflicts
    if report.conflict_causality:
        lines.append(f"\n# Version Conflicts Detected: {len(report.conflict_causality)}\n")
        for c in report.conflict_causality:
            lines.append(f"#   [{c.severity.upper()}] {c.package}: {' vs '.join(c.specs)}\n")
    else:
        lines.append("\n# Version Conflicts: None detected\n")

    # Untracked wheels
    if report.untracked_wheels:
        lines.append(f"\n# Untracked Wheels ({len(report.untracked_wheels)}):\n")
        for w in report.untracked_wheels:
            lines.append(f"#   {w}\n")

    # Version mismatches from installed packages
    if report.version_mismatches:
        lines.append(f"\n# Version Mismatches ({len(report.version_mismatches)}):\n")
        for m in report.version_mismatches:
            lines.append(f"#   {m}\n")

    # Wheel compatibility
    wheels = [r for r in url_results if getattr(r, "is_wheel", False)] # (if we had them in results)
    # Actually we have specialized list in the caller. 
    # Let's just use the repo's current specialized state if possible, 
    # but the report receives only report and url_results.
    # I will add 'wheel_results' to the report if needed, 
    # but for now I'll just check if untracked_wheels mentioned it.
    
    return lines
